DELETE FROM TRANSFERS;
INSERT INTO TRANSFERS(ID, FROMID, TOID, AMOUNT, TS) VALUES (1, 1, 2, 1000, 1);
INSERT INTO TRANSFERS(ID, FROMID, TOID, AMOUNT, TS) VALUES (2, 2, 5, 2000, 2);
INSERT INTO TRANSFERS(ID, FROMID, TOID, AMOUNT, TS) VALUES (3, 3, 2, 1500, 3);
INSERT INTO TRANSFERS(ID, FROMID, TOID, AMOUNT, TS) VALUES (4, 2, 3, 1400, 4);
INSERT INTO TRANSFERS(ID, FROMID, TOID, AMOUNT, TS) VALUES (5, 1, 4, 1200, 5);